---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install molecule

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - molecule lint
  - molecule syntax
  - molecule dependency
  - molecule create
  - molecule converge
  - molecule idempotence
  - molecule verify

  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook -c local tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
