---
# tasks file for harden-ssh

# Start off with a common blank slate
- include: "openssh-server-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
# Address Weak Ciphers and MACs
- include: Weak-Ciphers-CVE-2008-5161.yml
# Address ICMP  timestamp issues.
- include: ICMP-Timestamp-CVE-1999-0524.yml
# - include: apache stuff
# - include: ntp stuff
