---
- name: Stop insecure services
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ unnecessary_services[ansible_distribution]}}"

- name: Ensure that insecure services are disabled
  service:
    name: "{{ item }}"
    enabled: no
  with_items: "{{ unnecessary_services[ansible_distribution]}}"
