---
- name: Ensure that weak ciphers are removed
  blockinfile:
    marker: "#{mark} CVE-2008-5161"
    dest: /etc/ssh/sshd_config
    block: |
      Ciphers aes128-ctr,aes192-ctr,aes256-ctr
      MACs hmac-sha1,hmac-ripemd160
    state: present
    insertafter: "EOF"
    validate: '/usr/sbin/sshd -t -f %s'
  notify:
    - restart ssh

- name: wait for ssh to come back
  become: false
  local_action:
    module: wait_for
    port: 22
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    search_regex: "OpenSSH"
